# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 831b0f817f44f61e6640c7d49a130622c188ce0d449a971ab37f6cd52dc74e980e447c556dfb5ab7d2e734ee4d93c6684c04a92a3a57cc39de86687e306e7ce8

test:
  secret_key_base: ae4cc5e9c5e36e70d2a71b5d00460803a71b2c7ed62d959c0805a3c8097aef2521dcf1ac193eee3496e576b0fccf2bfb394412764a4c090e20ffc19e30914e83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
