defaults: &defaults
  wechat:
    client_id: wx0e413d605383490e

development:
  <<: *defaults
  base: http://jt.fannybay.net

test:
  <<: *defaults

production:
  <<: *defaults
  base: http://jt.fannybay.net