defaults: &defaults
  wechat:
    appid: wx0e413d605383490e
    secret: cbcffda6ee24824dc37cc33fa76d3801
    
development:
  <<: *defaults
  base: http://jt.fannybay.net

test:
  <<: *defaults

production:
  <<: *defaults
  base: http://jt.fannybay.net