defaults: &defaults
  wechat:
    client_id: wx0e413d605383490e

development:
  <<: *defaults
  base: http://localhost:3000

test:
  <<: *defaults

production:
  <<: *defaults
  base: http://www.xxx.com